# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "fixit-bundle"

[hugoVersion]
extended = true
min = "0.154.5"
